version: '2'
services:
  mysql:
    image: mysql:8.0.19
    container_name: mysql-dev-server-80
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_DATABASE=my_db
      - MYSQL_USER=dev_admin
      - MYSQL_PASSWORD=p455w0rd
    ports:
      - "3306:3306"
